# Generated by Django 4.0 on 2021-12-22 12:46

import datetime
from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('origin', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('departure_date', models.DateField(default=datetime.date(2021, 12, 23))),
                ('plane_type', models.CharField(choices=[('economic', 'econimic class'), ('business', 'business class'), ('first_class', 'first class')], default='economic', max_length=100)),
            ],
            managers=[
                ('records', django.db.models.manager.Manager()),
            ],
        ),
    ]
