# Generated by Django 4.0 on 2021-12-22 12:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='passengers',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
