# Generated by Django 2.2.2 on 2019-06-12 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190607_0829'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='name',
        ),
    ]
