# Generated by Django 2.2.2 on 2019-06-26 08:39

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0005_remove_flight_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='passengers',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='flight',
            name='departure_date',
            field=models.DateField(default=datetime.date(2019, 6, 27)),
        ),
        migrations.AlterField(
            model_name='flight',
            name='return_date',
            field=models.DateField(default=datetime.date(2019, 6, 29)),
        ),
    ]
