# Generated by Django 2.2.2 on 2019-06-28 17:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20190626_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='departure_date',
            field=models.DateField(default=datetime.date(2019, 6, 29)),
        ),
        migrations.AlterField(
            model_name='flight',
            name='return_date',
            field=models.DateField(default=datetime.date(2019, 7, 1)),
        ),
    ]
