# Generated by Django 2.2.2 on 2019-06-28 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20190628_1707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='return_date',
        ),
    ]
