# Generated by Django 2.2.3 on 2021-09-24 13:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_flight_return_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plane',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=512, null=True)),
                ('max_number_of_seats', models.IntegerField(default=50)),
            ],
        ),
        migrations.AlterField(
            model_name='flight',
            name='departure_date',
            field=models.DateField(default=datetime.date(2021, 9, 25)),
        ),
        migrations.AddField(
            model_name='flight',
            name='plane',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Plane'),
        ),
    ]
