# Generated by Django 2.2.3 on 2021-12-10 19:11

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_flight_return_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plane',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=256)),
                ('name', models.CharField(max_length=256)),
                ('model', models.CharField(max_length=256)),
                ('capacity', models.IntegerField(default=1)),
            ],
        ),
        migrations.AlterField(
            model_name='flight',
            name='departure_date',
            field=models.DateField(default=datetime.date(2021, 12, 11)),
        ),
        migrations.AlterField(
            model_name='flight',
            name='plane_type',
            field=models.CharField(choices=[('economic', 'economic class'), ('business', 'business class'), ('first_class', 'first class')], default='economic', max_length=100),
        ),
        migrations.AddField(
            model_name='flight',
            name='plane',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Plane'),
        ),
    ]
