# Generated by Django 2.2.3 on 2021-09-24 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20210924_1331'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plane',
            old_name='max_number_of_seats',
            new_name='number_of_seats',
        ),
    ]
